(ns org.nd4j.linalg.api.ops.impl.accum.bp.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.nd4j.linalg.api.ops.impl.accum.bp.BaseReductionBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.CumProdBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.CumSumBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.DotBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.MaxBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.MeanBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.MinBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.Norm1Bp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.Norm2Bp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.NormMaxBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.ProdBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.SquaredNormBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.StandardDeviationBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.SumBp])
(require '[org.nd4j.linalg.api.ops.impl.accum.bp.VarianceBp])
