(ns com.atilika.kuromoji.dict.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.atilika.kuromoji.dict.CharacterDefinitions])
(require '[com.atilika.kuromoji.dict.ConnectionCosts])
(require '[com.atilika.kuromoji.dict.Dictionary])
(require '[com.atilika.kuromoji.dict.DictionaryEntryBase])
(require '[com.atilika.kuromoji.dict.DictionaryField])
(require '[com.atilika.kuromoji.dict.GenericDictionaryEntry$Builder])
(require '[com.atilika.kuromoji.dict.GenericDictionaryEntry])
(require '[com.atilika.kuromoji.dict.InsertedDictionary])
(require '[com.atilika.kuromoji.dict.TokenInfoDictionary])
(require '[com.atilika.kuromoji.dict.UnknownDictionary])
(require '[com.atilika.kuromoji.dict.UserDictionary$UserDictionaryMatch])
(require '[com.atilika.kuromoji.dict.UserDictionary])
