(ns org.nd4j.linalg.primitives.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.nd4j.linalg.primitives.AtomicBoolean])
(require '[org.nd4j.linalg.primitives.AtomicDouble])
(require '[org.nd4j.linalg.primitives.Counter])
(require '[org.nd4j.linalg.primitives.CounterMap])
(require '[org.nd4j.linalg.primitives.ImmutablePair])
(require '[org.nd4j.linalg.primitives.ImmutableQuad])
(require '[org.nd4j.linalg.primitives.ImmutableTriple])
(require '[org.nd4j.linalg.primitives.Optional])
(require '[org.nd4j.linalg.primitives.Pair])
(require '[org.nd4j.linalg.primitives.Quad])
(require '[org.nd4j.linalg.primitives.SynchronizedObject])
(require '[org.nd4j.linalg.primitives.Triple])
