(ns org.datavec.api.writable.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.datavec.api.writable.ArrayWritable])
(require '[org.datavec.api.writable.BooleanWritable$Comparator])
(require '[org.datavec.api.writable.BooleanWritable])
(require '[org.datavec.api.writable.ByteWritable$Comparator])
(require '[org.datavec.api.writable.ByteWritable])
(require '[org.datavec.api.writable.BytesWritable])
(require '[org.datavec.api.writable.DoubleWritable$Comparator])
(require '[org.datavec.api.writable.DoubleWritable])
(require '[org.datavec.api.writable.FloatWritable$Comparator])
(require '[org.datavec.api.writable.FloatWritable])
(require '[org.datavec.api.writable.IntWritable$Comparator])
(require '[org.datavec.api.writable.IntWritable])
(require '[org.datavec.api.writable.LongWritable$Comparator])
(require '[org.datavec.api.writable.LongWritable$DecreasingComparator])
(require '[org.datavec.api.writable.LongWritable])
(require '[org.datavec.api.writable.NDArrayWritable])
(require '[org.datavec.api.writable.NullWritable])
(require '[org.datavec.api.writable.Text$Comparator])
(require '[org.datavec.api.writable.Text])
(require '[org.datavec.api.writable.UnsafeWritableInjector])
(require '[org.datavec.api.writable.Writable])
(require '[org.datavec.api.writable.WritableFactory])
(require '[org.datavec.api.writable.WritableType])
