(ns org.nd4j.weightinit.impl.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.nd4j.weightinit.impl.ConstantInitScheme])
(require '[org.nd4j.weightinit.impl.DistributionInitScheme])
(require '[org.nd4j.weightinit.impl.IdentityInitScheme])
(require '[org.nd4j.weightinit.impl.LecunUniformInitScheme])
(require '[org.nd4j.weightinit.impl.NDArraySupplierInitScheme$NDArraySupplier])
(require '[org.nd4j.weightinit.impl.NDArraySupplierInitScheme])
(require '[org.nd4j.weightinit.impl.OneInitScheme])
(require '[org.nd4j.weightinit.impl.ReluInitScheme])
(require '[org.nd4j.weightinit.impl.ReluUniformInitScheme])
(require '[org.nd4j.weightinit.impl.SigmoidUniformInitScheme])
(require '[org.nd4j.weightinit.impl.UniformInitScheme])
(require '[org.nd4j.weightinit.impl.VarScalingNormalFanAvgInitScheme])
(require '[org.nd4j.weightinit.impl.VarScalingNormalFanInInitScheme])
(require '[org.nd4j.weightinit.impl.VarScalingNormalFanOutInitScheme])
(require '[org.nd4j.weightinit.impl.VarScalingNormalUniformFanInInitScheme])
(require '[org.nd4j.weightinit.impl.VarScalingNormalUniformFanOutInitScheme])
(require '[org.nd4j.weightinit.impl.VarScalingUniformFanAvgInitScheme])
(require '[org.nd4j.weightinit.impl.XavierFanInInitScheme])
(require '[org.nd4j.weightinit.impl.XavierInitScheme])
(require '[org.nd4j.weightinit.impl.XavierUniformInitScheme])
(require '[org.nd4j.weightinit.impl.ZeroInitScheme])
