(ns org.deeplearning4j.text.sentenceiterator.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.deeplearning4j.text.sentenceiterator.AggregatingSentenceIterator$Builder])
(require '[org.deeplearning4j.text.sentenceiterator.AggregatingSentenceIterator])
(require '[org.deeplearning4j.text.sentenceiterator.BaseSentenceIterator])
(require '[org.deeplearning4j.text.sentenceiterator.BasicLineIterator])
(require '[org.deeplearning4j.text.sentenceiterator.BasicResultSetIterator])
(require '[org.deeplearning4j.text.sentenceiterator.CollectionSentenceIterator])
(require '[org.deeplearning4j.text.sentenceiterator.FileSentenceIterator])
(require '[org.deeplearning4j.text.sentenceiterator.LineSentenceIterator])
(require '[org.deeplearning4j.text.sentenceiterator.MutipleEpochsSentenceIterator])
(require '[org.deeplearning4j.text.sentenceiterator.PrefetchingSentenceIterator$Builder])
(require '[org.deeplearning4j.text.sentenceiterator.PrefetchingSentenceIterator])
(require '[org.deeplearning4j.text.sentenceiterator.SentenceIterator])
(require '[org.deeplearning4j.text.sentenceiterator.SentencePreProcessor])
(require '[org.deeplearning4j.text.sentenceiterator.StreamLineIterator$Builder])
(require '[org.deeplearning4j.text.sentenceiterator.StreamLineIterator])
(require '[org.deeplearning4j.text.sentenceiterator.SynchronizedSentenceIterator])
(require '[org.deeplearning4j.text.sentenceiterator.UimaResultSetIterator])
(require '[org.deeplearning4j.text.sentenceiterator.UimaSentenceIterator])
