(ns org.deeplearning4j.text.documentiterator.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.deeplearning4j.text.documentiterator.AsyncLabelAwareIterator])
(require '[org.deeplearning4j.text.documentiterator.BasicLabelAwareIterator$Builder])
(require '[org.deeplearning4j.text.documentiterator.BasicLabelAwareIterator])
(require '[org.deeplearning4j.text.documentiterator.DocumentIterator])
(require '[org.deeplearning4j.text.documentiterator.FileDocumentIterator])
(require '[org.deeplearning4j.text.documentiterator.FileLabelAwareIterator$Builder])
(require '[org.deeplearning4j.text.documentiterator.FileLabelAwareIterator])
(require '[org.deeplearning4j.text.documentiterator.FilenamesLabelAwareIterator$Builder])
(require '[org.deeplearning4j.text.documentiterator.FilenamesLabelAwareIterator])
(require '[org.deeplearning4j.text.documentiterator.LabelAwareDocumentIterator])
(require '[org.deeplearning4j.text.documentiterator.LabelAwareIterator])
(require '[org.deeplearning4j.text.documentiterator.LabelledDocument])
(require '[org.deeplearning4j.text.documentiterator.LabelsSource])
(require '[org.deeplearning4j.text.documentiterator.SimpleLabelAwareIterator])
