(ns org.deeplearning4j.zoo.model.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.deeplearning4j.zoo.model.AlexNet])
(require '[org.deeplearning4j.zoo.model.Darknet19])
(require '[org.deeplearning4j.zoo.model.FaceNetNN4Small2])
(require '[org.deeplearning4j.zoo.model.InceptionResNetV1])
(require '[org.deeplearning4j.zoo.model.LeNet])
(require '[org.deeplearning4j.zoo.model.NASNet])
(require '[org.deeplearning4j.zoo.model.ResNet50])
(require '[org.deeplearning4j.zoo.model.SimpleCNN])
(require '[org.deeplearning4j.zoo.model.SqueezeNet])
(require '[org.deeplearning4j.zoo.model.TextGenerationLSTM])
(require '[org.deeplearning4j.zoo.model.TinyYOLO])
(require '[org.deeplearning4j.zoo.model.UNet])
(require '[org.deeplearning4j.zoo.model.VGG16])
(require '[org.deeplearning4j.zoo.model.VGG19])
(require '[org.deeplearning4j.zoo.model.Xception])
(require '[org.deeplearning4j.zoo.model.YOLO2])
